  <!-- Footer Ad -->");
document.write("<table width=\"100%\" border=\"0\" bgcolor=\"#0066FF\" style=\"border-bottom-color:#000099\">");
   <tr>");
     <td><a href=\"sitemap\" ><strong><font face=\"Arial\" size=\"1\" color=\"white\">Sitemap <\/font><\/strong><\/a><\/td> ");
     <td align=\"right\"><a href=\"http:\/\/www.jamstechs.com\"  ><strong><font face=\"Arial\" size=\"1\" color=\"white\" >&#169;Jamstechs (2012) <\/font><\/strong> <\/td>");
   <\/tr>");
document.write("<\/table>");
   <table width=\"100%\" border=\"1\" >");
     ");
       <tr>");
     <td width=\"161\" align=\"center\" valign=\"middle\" bgcolor=\"#FFCCFF\" ><p><font face=\"Courier New, Courier, monospace\" size=\"+1\"  color=\"#999999\"> This space is available for advertisement<\/font><\/p>");
       <p>&nbsp;please contact admanager@divinetraveller.net<\/p><\/td>");
document.write("");
     <td width=\"60%\" height=\"110\" align=\"left\" valign=\"middle\" bgcolor=\"#006600\" ><p><font face=\"Arial, Helvetica, sans-serif\" color=\"#FFFF33\">   <br\/>");
       &nbsp; &nbsp;Advertise and  reach");
       thousands  of genuine users. Select any of the hundreds of website pages of temple cities and towns in South India and other  parts of India in this website.<\/font><\/p>");
       <p><font face=\"Arial, Helvetica, sans-serif\" color=\"#FFFF33\">&nbsp; &nbsp; The revenue from the advertisements goes towards charity,donations to needy temples and maintenance of this site.<\/font> <font color=\"#FFFF33\" face=\"Arial, Helvetica, sans-serif\">Tariff and details please contact <\/font>       <font color=\"#FFFFFF\" face=\"Verdana, Geneva, sans-serif\" style=\"font-style:italic\">&nbsp; &nbsp;&nbsp; &nbsp;admanager@divinetraveller.net<\/font><\/p>");
document.write("");
document.write("");
document.write("<\/td>");
document.write("<td width=\"161\" align=\"center\" valign=\"middle\" bgcolor=\"#FFCCFF\" ><p><font face=\"Courier New, Courier, monospace\" size=\"+1\"  color=\"#999999\"> This space is available for advertisement<\/font><\/p>");
       <p>&nbsp;please contact admanager@divinetraveller.net<\/p><\/td>");
   <\/tr>");
   <\/table>");
   ");
  <!-- End of Foot ad --> ");
