document.write("");
document.write(" ");
document.write("<div style=\"border:1px solid blue;\">");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"white\"> Temples of Tamil Nadu <\/font><\/strong><\/td>");
document.write("       <\/tr> 	   ");
document.write("	 <tr>");
document.write("		<td width=100% bgcolor=\"#99CCFF\" align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Madurai & Around <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("       <\/table> ");
document.write("	   ");
document.write("	   <ul class=\"nav\" > "); 
document.write("	   ");

document.write("	   <li><a  href=\"alagarkoil.html\">&#45 Algarkoil <\/a><\/li>	  ");
document.write("	   <li><a href=\"madurai.html\"  >&#45 Madurai Meenakshi <\/a><\/li>");

document.write("	   <div onClick=\"openClose('tn')\" class=\"main\"><span id=\"tick_tn\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("	 <div id=\"tn\" class=\"links\">   ");
document.write("	   <li><a  href=\"pazhacholai.html\">&#45 Pazhamudircholai <\/a><\/li>	  ");

document.write("	   <li><a  href=\"rameshwaram.html\">&#45 Rameswaram <\/a><\/li>	  ");
document.write("	   <li><a  href=\"srivilliputhur.html\">&#45 Srivilliputhur <\/a><\/li>	  ");
document.write("	   <li><a  href=\"thirumokur.html\">&#45 Thiru Moghur <\/a><\/li>	  ");


document.write("	   <li><a  href=\"thiruparankunram.html\">&#45 Thirupparamkunram<\/a><\/li>");
document.write("	  <\/ul>");
document.write("	  ");
document.write("	<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Tiruvarur <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("	   ");
document.write("	   <ul class=\"nav\" > ");
document.write("	   <li><a  href=\"mannargudi.html\">&#45 Mannargudi <\/a><\/li>");
document.write("	   <li><a  href=\"thirukollikadu.html\">&#45 Thirukollikadu <\/a><\/li>");
document.write("	   <li><a  href=\"thirukanmangai.html\">&#45 Tirukannamangai <\/a><\/li>");
document.write("	   ");

document.write("	   <div onClick=\"openClose('tvr')\" class=\"main\"><span id=\"tick_tvr\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("	 <div id=\"tvr\" class=\"links\"> ");
document.write("	   <li><a  href=\"thiruvarur.html\">&#45 Thyagaraja Temple,Tiruvarur<\/a><\/li>");
document.write("	   <li><a  href=\"sirupuliyur.html\">&#45 Tirusirupuliyur<\/a><\/li>");
document.write("	   <li><a  href=\"vaduvur.html\">&#45 Vaduvur <\/a><\/li>");

document.write("	     ");
document.write("	   ");
document.write("	   ");
document.write("	   ");
document.write("	  <\/ul>");
document.write("	  ");
document.write("        ");
document.write("      <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Sivaganga <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("	   ");
document.write("	   <ul class=\"nav\" > ");
document.write("	   <li><a  href=\"kunnakudi.html\">&#45 Kunnakudi <\/a><\/li>");
document.write("	   ");
document.write("	   <li><a  href=\"Thirukoshtiyur.html\">&#45 Thirukoshtiyur <\/a><\/li>");
document.write("	     ");
document.write("	   <li><a  href=\"pillayarpatti.html\">&#45 Pillayarpatti <\/a><\/li>");
document.write("	   <div onClick=\"openClose('sg')\" class=\"main\"><span id=\"tick_sg\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("	 <div id=\"sg\" class=\"links\"> ");
document.write("	   <li><a  href=\"vairavanpatti.html\">&#45 Vairavan patti <\/a><\/li>");
document.write("	   ");
document.write("	  <\/ul>");
document.write("	  ");
document.write("      ");
document.write("	   ");
document.write("	   <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Kumbakonam & around <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("	   ");
document.write("");
document.write("");
document.write(" ");

document.write("<ul class=\"nav\"  >");
document.write("      <li><a   href=\"alangudi.html\">&#45 Alangudi-Guru <\/a><\/li>");
document.write("	  ");
document.write("	  <li><a href=\"ayyavadi.html\">&#45 Ayyavadi-Prithiyangara <\/a><\/li>");
document.write("      ");
document.write("     ");
document.write("	  ");
document.write("	<div onClick=\"openClose('kum')\" class=\"main\"><span id=\"tick_kum\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("	");
document.write("      <div id=\"kum\" class=\"links\">  ");
document.write("	   ");

document.write("	   <li><a  href=\"Gagraharam.html\">&#45 Ganapathy Agraharam <\/a><\/li>");
document.write("	    <li><a  href=\"kabithalam.html\">&#45 Kabisthalam <\/a><\/li>");
document.write("	  <li><a href=\"koothanur.html\">&#45 Koothanoor-Saraswathy <\/a><\/li>");
document.write("	   <li><a href=\"pboothankudi.html\">&#45 Pullamboothamkudi <\/a><\/li>");
document.write("	 ");
document.write("	  ");
document.write("	  <li><a  href=\"thirunageswaram.html\">&#45 Thirunageswaram-Raghu <\/a><\/li>");
document.write("	 ");

document.write("	  <li><a  href=\"thirunarayur.html\">&#45 Nachiyarkoil <\/a><\/li>");
document.write("	   <li><a  href=\"nathankoil.html\">&#45 Nathankoil <\/a><\/li>");
document.write("	  <li><a  href=\"pateeswaram.html\">&#45 Patteeswaram <\/a><\/li>");
document.write("	  <li><a  href=\"sarngapani.html\">&#45 Sarngapani <\/a><\/li>");
document.write("	   <li><a  href=\"suriyanar.html\">&#45 Suryanarkoil <\/a><\/li>");
document.write("	  ");
document.write("	  ");

document.write("	  <li><a href=\"swamimalai.html\">&#45 Swamimalai <\/a><\/li>");
document.write("	  <li><a  href=\"thiruadanoor.html\">&#45 ThiruAadhanoor <\/a><\/li>");
//document.write("	  <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Thirumanajeri <\/a><\/li>");
document.write("	  <li><a  href=\"thirumeyachur.html\">&#45 Thirumeyachur <\/a><\/li>");
document.write("	  <li><a  href=\"thirubhuvanam.html\">&#45 Thirubhuvanam <\/a><\/li>");
document.write("	  <li><a  href=\"thiruvidaimaruthur.html\">&#45 Thiruvidaimaruthur <\/a><\/li>");
document.write("	  <li><a href=\"thirunageswaram.html\">&#45 Thirunageswaram-Raghu <\/a><\/li>");
document.write("	  <li><a   href=\"thiruvalanchuzhi.html\">&#45 Thiruvalanchuzhi<\/a><\/li>");
document.write("	  <li><a  href=\"velliyankudi.html\">&#45 Thiruvelliyankudi<\/a><\/li>");
document.write("	  <li><a  href=\"thirukarugavur.html\">&#45 Thirugarugavur <\/a><\/li>");
document.write("	  <li><a  href=\"thingalaur.html\">&#45 Thingalur <\/a><\/li>");

document.write("	  <li><a  href=\"oppilliappan.html\">&#45 Uppiliappan <\/a><\/li>");

document.write("	  ");
document.write("");
document.write("<\/ul>");
document.write("");
document.write(" ");

document.write("  <ul class=\"nav\"  >  ");
document.write("      ");
document.write("	  <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >   ");
document.write("   <tr>");
document.write("<td width=100% bgcolor=\"#99CCFF\" align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Chidambaram,Sirkali<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a  href=\"thillai.html\"> &#45 Chidambaram<\/a><\/li>");
document.write("	   <div onClick=\"openClose('cs')\" class=\"main\"><span id=\"tick_cs\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"cs\" class=\"links\">");
document.write("             ");
document.write("	  <li><a  href=\"sirkali.html\">&#45 Sirkazhi <\/a><\/li>");
document.write("	  <li><a  href=\"thirukadaiyur.html\">&#45 Thirukadaiyur<\/a><\/li>");
document.write("	  <li><a href=\"thiruvengadu.html\">&#45 Thiruvengadu<\/a><\/li>");
document.write("	  <li><a href=\"thirunallaru.html\">&#45 Thirunallaru-Saneeswaran <\/a><\/li>");
document.write("	  <li><a  href=\"sevvai.html\">&#45 Vaitheeswarankoil <\/a><\/li>");
document.write("      ");
document.write("        ");
document.write("    <\/ul>");


document.write(" <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Tiruchirapalli <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("<ul class=\"nav\" >	  ");
document.write("       ");
document.write("	   ");
document.write("	  <li><a  href=\"anbil_sivan.html\">&#45 Anbil-Brahmapureeswarar<\/a><\/li>");
document.write("       <li><a  href=\"srirangam.html\">&#45 Srirangam <\/a><\/li>");
document.write("	  <li><a   href=\"samayapuram.html\">&#45 Samayapuram<\/a><\/li>");
document.write("	  <li><a   href=\"thiruvanaikoil.html\">&#45 Thiruanaikoil <\/a><\/li>");
document.write("	  <div onClick=\"openClose('kanch')\" class=\"main\"><span id=\"tick_kanch\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kanch\" class=\"links\">");
document.write("	  <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Thiruvellarai <\/a><\/li>");
document.write("	  <li><a href=\"malaikottai.html\">&#45 Uchipillayar <\/a><\/li>");
document.write("	  <li><a  href=\"vayalur.html\">&#45 Vayalur Murugan <\/a><\/li>");
  
document.write("	  <li><a href=\"vekkali.html\">&#45Vekkali Amman <\/a><\/li>");
document.write("	  <li><a href=\"panchavarnaswamy.html\">&#45Panchavarnaswamy <\/a><\/li>");


document.write("  ");
document.write(" <\/ul>	");
document.write("  ");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Kanchipuram<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write(" ");
document.write("<ul class=\"nav\" >	  ");
document.write("       ");
document.write("	    <li><a href=\"ekambareshwar.html\">&#45 Ekambareswarar <\/a><\/li>");
document.write("       <li><a href=\"kamatchi.html\">&#45 Kamatchi Amman <\/a><\/li>");
document.write("	  ");
document.write("	  ");
document.write("	  <div onClick=\"openClose('kanchi')\" class=\"main\"><span id=\"tick_kanchi\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kanchi\" class=\"links\">");
document.write("	  <li><a  href=\"ashtapuja.html\">&#45 Ashtapuja Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"nilathingal.html\">&#45 Nilathingal Perumal <\/a><\/li>");
document.write("	   <li><a  href=\"pandavathudhar.html\">&#45 Pandavathoodhar perumal <\/a><\/li>");
document.write("	    <li><a  href=\"pavalavannar.html\">&#45 Pavalavannar perumal <\/a><\/li>");
document.write("	  <li><a  href=\"yadodkari.html\">&#45 Thiru Vekka <\/a><\/li>  ");
document.write("	  <li><a  href=\"thirupukkuzhi.html\">&#45 ThiruPutkuzhi <\/a><\/li>");
document.write("	  <li><a  href=\"thiruvelukkai.html\">&#45 Thiru Velukkai <\/a><\/li>");
document.write("	  <li><a  href=\"thiruooragam.html\">&#45 Ulagalandha Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"varadaraja.html\">&#45 Varadaraja Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"thiruthanka.html\">&#45 Vilakoli Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"vaikunta.html\">&#45 Vaikunda Perumal <\/a><\/li>");
document.write("	  ");
document.write("  ");
document.write(" <\/ul>");
document.write("");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Chennai & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write(" <ul class=\"nav\" >      ");
document.write("       ");
document.write("	   ");
document.write("	     ");
document.write("		");
document.write("	  <li><a  href=\"gnayiru-pushparatheswarar.html\">&#45Gnayiru Pushparatheeswarar<\/a><\/li>");
document.write("	  <li><a  href=\"kalikambal.html\">&#45 Kaligambal <\/a><\/li>");
document.write("	  ");

document.write("	  <li><a  href=\"mangadu.html\">&#45 Mangadu <\/a><\/li>");
document.write("	  <li><a  href=\"marundeeswar.html\">&#45 Marundeeswarar<\/a><\/li>");
document.write("	  <li><a  href=\"mylai.html\">&#45 Mylai Kapaleeswarar <\/a><\/li>");

document.write("	   <div onClick=\"openClose('chenn')\" class=\"main\"><span id=\"tick_chenn\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"chenn\" class=\"links\">");
document.write("	  <li><a  href=\"pancheti.html\">&#45 Pancheshti<\/a><\/li>");
document.write("	  <li><a  href=\"thiruvidenthai.htm\">&#45 Thiruvidanthai<\/a><\/li>");
document.write("	  <li><a  href=\"thiruverkadu.html\">&#45 Thiruverkadu <\/a><\/li>");

document.write("	  <li><a  href=\"tiruallikeni.html\">&#45 Tiruallikeni Parthasarathy <\/a><\/li>");
document.write("	  <li><a  href=\"thiruninravoor.html\">&#45 Thiruninravur <\/a><\/li>");
document.write("	  <li><a  href=\"thiruneermalai.html\">&#45Thiruneermalai <\/a><\/li>");
document.write("	  <li><a  href=\"underconstruction.html\">&#45 Thirumazhisai 2 <\/a><\/li>");
document.write("	  <li><a  href=\"thiruvaluri.html\">&#45 Tiruvallur <\/a><\/li>");
document.write("	  <li><a  href=\"vadapalani.html\">&#45Vadapalani <\/a><\/li>");

document.write("	   <li><a title=\"under Construction\" href=\"underconstruction.html\">&#45 Pancheshti<\/a><\/li>");

document.write("<\/ul>");
document.write("");

document.write(" <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Tiruvannmalai & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write(" <ul class=\"nav\" >      ");
document.write("       ");
document.write("	   <li><a href=\"thiruvanamalai.html\">&#45 Tiruvannamalai <\/a><\/li>");
document.write("	   <li><a  href=\"thiruvennainallur.html\">&#45 Thiruvennainallur<\/a><\/li>");
document.write("	   <li><a title=\"under Construction\" href=\"underconstruction.html\">&#45 Tirukoilur<\/a><\/li>");

document.write(" <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Tanjavur & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write(" <ul class=\"nav\" >      ");
document.write("       ");
document.write("	   <li><a title=\"under Construction\" href=\"underconstruction.html\">&#45 Tanjavur <\/a><\/li>");
document.write("	   <li><a  href=\"thiruvayaru.html\">&#45 Thiruvayaru-Aiyarappan<\/a><\/li>");
document.write("	   <li><a  href=\"thirukandiyur_sivan.html\">&#45 Thirukandiyur Sivan<\/a><\/li>");
//document.write("	   <li><a title=\"under Construction\" href=\"underconstruction.html\">&#45 Tanjavur <\/a><\/li>");
document.write("	   <li><a  href=\"varagur.html\">&#45 Varagur<\/a><\/li>");

document.write("<ul class=\"nav\" >	  ");
document.write("	   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("       <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Kerala <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("      ");
document.write("      <li><a  href=\"guruvayur.html\">&#45 Guruvayur <\/a><\/li>");
document.write("      <li><a  href=\"mammiyur.html\">&#45 Mammiyur <\/a><\/li>");
document.write("      <li><a  href=\"kaladi.html\">&#45 Kalady<\/a><\/li>");
document.write("      <li><a  href=\"meenkulathi.html\">&#45 Meenkulathy Bhagavathi<\/a><\/li>");
document.write("	   <div onClick=\"openClose('kerala')\" class=\"main\"><span id=\"tick_kerala\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kerala\" class=\"links\">");
document.write("	 <li ><a href=\"sabarimalai.html\"> &#45 Sabarimala<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Tiruvanathapuram&nbsp;&nbsp; Padmanabha Swamy <\/a><\/li>");
document.write("      ");
document.write("       <hr \/>");
document.write("	  <\/ul>");
document.write("	  ");
document.write("  <ul class=\"nav\" >");
document.write("     <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Karnataka <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("	   <li><a  href=\"baghamandla.html\">&#45 Baghamandala<\/a><\/li>");
document.write("     <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Dharamastala<\/a><\/li>");
document.write("     <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Horanad<\/a><\/li>");
document.write("      <li><a  href=\"sringeri.html\"><font size=\"2\"> &#45 Kateel<\/font><\/a><\/li>");
document.write("      <li><a  href=\"sringeri.html\"><font size=\"2\"> &#45 Kadri<\/font><\/a><\/li>");
document.write("      <li><a  href=\"sringeri.html\"><font size=\"2\"> &#45 Kukke Subramanya<\/font><\/a><\/li>");
document.write("     <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Mookambika<\/a><\/li>");
document.write("      <li><a  href=\"sringeri.html\"><font size=\"2\"> &#45 Sringeri<\/font><\/a><\/li>");
document.write("      ");
document.write("      ");
document.write("	   <div onClick=\"openClose('karna')\" class=\"main\"><span id=\"tick_karna\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"karna\" class=\"links\">");
document.write("      <li><a  href=\"talacauvery.html\">&#45 Talacauvery<\/a><\/li>");
document.write("	  <li><a  href=\"udupi2.html\">&#45 Udupi SriKrishna<\/a><\/li>");
document.write(" <\/ul>");
document.write(" ");
document.write(" <ul class=\"nav\" >");
document.write("	  ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Andhra Pradesh <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"lemonrasam.html\">&#45 Kalahasthi<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"jeerarasam.html\">&#45 Srisailam<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"pepperrasam.html\"> &#45 Tirupathi<\/a><\/li>");
document.write("	   <div onClick=\"openClose('ap')\" class=\"main\"><span id=\"tick_ap\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"ap\" class=\"links\">");
document.write("      ");
document.write("  <\/ul>");
document.write("  ");
document.write("  <ul class=\"nav\" >      ");
document.write("      ");
document.write("     ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Maharashtra <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a  href=\"mumbai-sidhivinayaka.html\"> &#45 Mumbai-Sri Sidhi Vinayak<\/a><\/li>");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Mumbai-Mumbadevi<\/a><\/li>");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Mumbai-Mahalakshmi<\/a><\/li>");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Ashta Vinayaka<\/a><\/li>");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Kholapur<\/a><\/li>");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Shirdi<\/a><\/li>");
document.write("        <div onClick=\"openClose('maha')\" class=\"main\"><span id=\"tick_maha\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"maha\" class=\"links\">       ");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Phanadripur<\/a><\/li>");
document.write("      <li><a  href=\"underconstruction.html\"> &#45 Sani Shinganapur<\/a><\/li>");

document.write("  <\/ul>");
document.write("  ");

document.write("  <ul class=\"nav\"  >  ");
document.write("      ");
document.write("	  <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Himachal Pradesh <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a  href=\"underconstruction.html\"><font color=\"red\"> &#45 Nainadevi<\/a></font><\/li>");
document.write("	   <div onClick=\"openClose('hp')\" class=\"main\"><span id=\"tick_hp\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"hp\" class=\"links\">");
document.write("             ");
document.write("      ");
document.write("        ");
document.write("    <\/ul>");
document.write("	<\/div>");
