document.write("");
document.write(" ");
document.write("<div style=\"border:1px solid blue;\">");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"white\"> Temples of Tamil Nadu <\/font><\/strong><\/td>");
document.write("       <\/tr> 	   ");
document.write("       <\/table> ");
document.write("	   ");
document.write("	   <ul class=\"nav\" > ");
document.write("	   ");
document.write("	   <li><a title=\"under Construction\" href=\"#\">&#45 Madurai Meenakshi <\/a><\/li>");
document.write("	   <li><a title=\"under Construction\" href=\"#\">&#45 Mannargudi <\/a><\/li>");
document.write("	   <div onClick=\"openClose('tn')\" class=\"main\"><span id=\"tick_tn\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("	 <div id=\"tn\" class=\"links\">   ");
document.write("	   <li><a title=\"under Construction\" href=\"#\">&#45 Rameswaram <\/a><\/li>	  ");
document.write("	   <li><a  href=\"thirukollikadu.html\">&#45 Thirukollikadu <\/a><\/li>");
document.write("	   <li><a title=\"under Construction\" href=\"#\">&#45 Tiruvannamalai <\/a><\/li>");
document.write("	  <\/ul>");
document.write("	  ");
document.write("	<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Tiruvarur <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("	   ");
document.write("	   <ul class=\"nav\" > ");
document.write("	   <li><a  href=\"#\">&#45 Varagur <\/a><\/li>");
document.write("	   ");
document.write("	   <li><a  href=\"#\">&#45 Thirukoshtiyur <\/a><\/li>");
document.write("	     ");
document.write("	   ");
document.write("	   <div onClick=\"openClose('tvr')\" class=\"main\"><span id=\"tick_tvr\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("	 <div id=\"tvr\" class=\"links\"> ");
document.write("	   ");
document.write("	   ");
document.write("	  <\/ul>");
document.write("	  ");
document.write("        ");
document.write("      <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Sivaganga <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("	   ");
document.write("	   <ul class=\"nav\" > ");
document.write("	   <li><a  href=\"kunnakudi.html\">&#45 Kunnakudi <\/a><\/li>");
document.write("	   ");
document.write("	   <li><a  href=\"Thirukoshtiyur.html\">&#45 Thirukoshtiyur <\/a><\/li>");
document.write("	     ");
document.write("	   <li><a  href=\"pillayarpatti.html\">&#45 Pillayarpatti <\/a><\/li>");
document.write("	   <div onClick=\"openClose('sg')\" class=\"main\"><span id=\"tick_sg\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("	 <div id=\"sg\" class=\"links\"> ");
document.write("	   <li><a  href=\"vairavanpatti.html\">&#45 Vairavan patti <\/a><\/li>");
document.write("	   ");
document.write("	  <\/ul>");
document.write("	  ");
document.write("      ");
document.write("	   ");
document.write("	   <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Kumbakonam & around <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("	   ");
document.write("");
document.write("");
document.write(" ");
document.write("<ul class=\"nav\"  >");
document.write("      <li><a  title=\"under Construction\" href=\"#\">&#45 Alangudi-Guru <\/a><\/li>");
document.write("	  ");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Ayyavadi-Prithiyangara <\/a><\/li>");
document.write("      ");
document.write("     ");
document.write("	  ");
document.write("	<div onClick=\"openClose('kum')\" class=\"main\"><span id=\"tick_kum\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("	");
document.write("      <div id=\"kum\" class=\"links\">  ");
document.write("	   ");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Chidambaram<\/a><\/li>");
document.write("	   <li><a  href=\"Gagraharam.html\">&#45 Ganapathy Agraharam <\/a><\/li>");
document.write("	    <li><a  href=\"kabithalam.html\">&#45 Kabisthalam <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Koothanoor-Saraswathy <\/a><\/li>");
document.write("	   <li><a title=\"under Construction\" href=\"pboothankudi.html\">&#45 Pullamboothamkudi <\/a><\/li>");
document.write("	 ");
document.write("	  ");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Thirunageswaram-Raghu <\/a><\/li>");
document.write("	 ");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Mannargudi <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Nachiyarkoil <\/a><\/li>");
document.write("	   <li><a  href=\"nathankoil.html\">&#45 Nathankoil <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Patteeswaram <\/a><\/li>");
document.write("	  <li><a  href=\"sarngapani.html\">&#45 Sarngapani <\/a><\/li>");
document.write("	   <li><a title=\"under Construction\" href=\"#\">&#45 Suryanarkoil <\/a><\/li>");
document.write("	  ");
document.write("	  ");
document.write("	  <li><a title=\"under Construction\" href=\"#\">&#45 Sirkazhi <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Swamimalai <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"thiruadanoor.html\">&#45 ThiruAadhanoor <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thirumanajeri <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thirukadaiyur<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thirunallaru-Saneeswaran <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thirubhuvanam <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thiruvidaimaruthur <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thirunageswaram-Raghu <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thiruvalanchuzhi<\/a><\/li>");
document.write("	  <li><a  href=\"velliyankudi.html\">&#45 Thiruvelliyankudi<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thirugarugavur <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thingalur <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thiruvayaru<\/a><\/li>");
document.write("	  <li><a  href=\"oppilliappan.html\">&#45 Uppiliappan <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Vaitheeswarankoil <\/a><\/li>");
document.write("	  ");
document.write("");
document.write("<\/ul>");
document.write("");
document.write(" ");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Tiruchirapalli <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write("<ul class=\"nav\" >	  ");
document.write("       ");
document.write("	    ");
document.write("       <li><a title=\"under Construction\"  href=\"#\">&#45 Srirangam <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Samayapuram<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thiruanaikoil <\/a><\/li>");
document.write("	  <div onClick=\"openClose('kanch')\" class=\"main\"><span id=\"tick_kanch\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kanch\" class=\"links\">");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Thiruanaikoil <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Uchipillayar <\/a><\/li>");
document.write("  ");
document.write(" <\/ul>	");
document.write("  ");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Kanchipuram<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write(" ");
document.write("<ul class=\"nav\" >	  ");
document.write("       ");
document.write("	    <li><a title=\"under Construction\"  href=\"#\">&#45 Ekambareswarar <\/a><\/li>");
document.write("       <li><a title=\"under Construction\"  href=\"#\">&#45 Kamatchi Amman <\/a><\/li>");
document.write("	  ");
document.write("	  ");
document.write("	  <div onClick=\"openClose('kanchi')\" class=\"main\"><span id=\"tick_kanchi\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kanchi\" class=\"links\">");
document.write("	  <li><a  href=\"ashtapuja.html\">&#45 Ashtapuja Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"nilathingal.html\">&#45 Nilathingal Perumal <\/a><\/li>");
document.write("	   <li><a  href=\"pandavathudhar.html\">&#45 Pandavathoodhar perumal <\/a><\/li>");
document.write("	    <li><a  href=\"pavalavannar.html\">&#45 Pavalavannar perumal <\/a><\/li>");
document.write("	  <li><a  href=\"yadodkari.html\">&#45 Thiru Vekka <\/a><\/li>  ");
document.write("	  <li><a  href=\"thirupukkuzhi.html\">&#45 ThiruPutkuzhi <\/a><\/li>");
document.write("	  <li><a  href=\"thiruvelukkai.html\">&#45 Thiru Velukkai <\/a><\/li>");
document.write("	  <li><a  href=\"thiruooragam.html\">&#45 Ulagalandha Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"varadaraja.html\">&#45 Varadaraja Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"thiruthanka.html\">&#45 Vilakoli Perumal <\/a><\/li>");
document.write("	  <li><a  href=\"vaikunta.html\">&#45 Vaikunda Perumal <\/a><\/li>");
document.write("	  ");
document.write("  ");
document.write(" <\/ul>");
document.write("");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\">Chennai & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>");
document.write(" <ul class=\"nav\" >      ");
document.write("       ");
document.write("	   ");
document.write("	     ");
document.write("		");
document.write("	  <li><a  href=\"kalikambal.html\">&#45 Kaligambal <\/a><\/li>");
document.write("	  ");
document.write("	  <li><a  href=\"mylai.html\">&#45 Mylai Kapaleeswarar <\/a><\/li>");
document.write("	   <div onClick=\"openClose('chenn')\" class=\"main\"><span id=\"tick_chenn\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"chenn\" class=\"links\">");
document.write("	  <li><a  href=\"thiruvidenthai.htm\">&#45 Thiruvidanthai<\/a><\/li>");
document.write("	  <li><a  href=\"tiruallikeni.html\">&#45 Tiruallikeni Parthasarathy <\/a><\/li>");
document.write("	  <li><a  href=\"thiruninravoor.html\">&#45 Thiruninravur <\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Siruvapuri <\/a><\/li>");
document.write("<\/ul>");
document.write("");
document.write("<ul class=\"nav\" >	  ");
document.write("	   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("       <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Kerala <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("      ");
document.write("      <li><a  href=\"guruvayur.html\">&#45 Guruvayur <\/a><\/li>");
document.write("      <li><a  href=\"mammiyur.html\">&#45 Mammiyur <\/a><\/li>");
document.write("      <li><a  href=\"kaladi.html\">&#45 Kalady<\/a><\/li>");
document.write("      <li><a  href=\"meenkulathi.html\">&#45 Meenkulathy Bhagavathi<\/a><\/li>");
document.write("	   <div onClick=\"openClose('kerala')\" class=\"main\"><span id=\"tick_kerala\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kerala\" class=\"links\">");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Sabarimala<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"#\">&#45 Tiruvanathapuram&nbsp;&nbsp; Padmanabha Swamy <\/a><\/li>");
document.write("      ");
document.write("       <hr \/>");
document.write("	  <\/ul>");
document.write("	  ");
document.write("  <ul class=\"nav\" >");
document.write("     <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Karnataka <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("	   <li><a  href=\"baghamandla.html\">&#45 Baghamandala<\/a><\/li>");
document.write("     <li><a title=\"under Construction\"  href=\"#\">&#45 Mookambika<\/a><\/li>");
document.write("      <li><a  href=\"sringeri.html\"><font size=\"2\"> &#45 Sringeri<\/font><\/a><\/li>");
document.write("      ");
document.write("      ");
document.write("	   <div onClick=\"openClose('karna')\" class=\"main\"><span id=\"tick_karna\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"karna\" class=\"links\">");
document.write("      <li><a  href=\"talacauvery.html\">&#45 Talacauvery<\/a><\/li>");
document.write("	  <li><a  href=\"udupi2.html\">&#45 Udupi SriKrishna<\/a><\/li>");
document.write(" <\/ul>");
document.write(" ");
document.write(" <ul class=\"nav\" >");
document.write("	  ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Andhra Pradesh <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"lemonrasam.html\">&#45 Kalahasthi<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"jeerarasam.html\">&#45 Srisailam<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"pepperrasam.html\"> &#45 Tirupathi<\/a><\/li>");
document.write("	   <div onClick=\"openClose('ap')\" class=\"main\"><span id=\"tick_ap\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"ap\" class=\"links\">");
document.write("      ");
document.write("  <\/ul>");
document.write("  ");
document.write("  <ul class=\"nav\" >      ");
document.write("      ");
document.write("     ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Maharashtra <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a  href=\"mumbai-sidhivinayaka.html\"> &#45 Mumbai-Sri Sidhi Vinayak<\/a><\/li>");
document.write("        <div onClick=\"openClose('maha')\" class=\"main\"><span id=\"tick_maha\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"maha\" class=\"links\">       ");
document.write("  <\/ul>");
document.write("  ");
document.write("  <ul class=\"nav\"  >  ");
document.write("      ");
document.write("	  <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Himachal Pradesh <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a  href=\"#\"> &#45 Nainadevi<\/a><\/li>");
document.write("	   <div onClick=\"openClose('hp')\" class=\"main\"><span id=\"tick_hp\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"hp\" class=\"links\">");
document.write("             ");
document.write("      ");
document.write("        ");
document.write("    <\/ul>");
document.write("	<\/div>");
