document.write("<table width=\"100%\" border=\"0\" bgcolor=\"#FFFFFF\" >");
document.write("  <tr>");
document.write("    <td width=\"20%\"><!--");
document.write("google_ad_client = \"ca-pub-2331677159054721\";");
document.write("\/* divine traveller page left ad *\/");
document.write("google_ad_slot = \"6796116034\";");
document.write("google_ad_width = 125;");
document.write("google_ad_height = 125;");
document.write("\/\/-->");
/*document.write("<\/script>"); 
document.write("<script type=\"text\/javascript\""); */
document.write("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js");
document.write("<\/td>");
document.write("");
document.write("    <td width=\"60%\"><!--");
document.write("google_ad_client = \"ca-pub-2331677159054721\";");
document.write("\/* divinetraveller top *\/");
document.write("google_ad_slot = \"3835976435\";");
document.write("google_ad_width = 728;");
document.write("google_ad_height = 90;");
document.write("\/\/-->");

document.write("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js");
document.write("<\/td>");
document.write("	");
document.write("    <td width=\"20%\"><!--");
document.write("google_ad_client = \"ca-pub-2331677159054721\";");
document.write("\/* divine traveller page left ad *\/");
document.write("google_ad_slot = \"6796116034\";");
document.write("google_ad_width = 125;");
document.write("google_ad_height = 125;");
document.write("\/\/-->");

document.write("");
document.write("");

document.write("src=\"http:\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js");
document.write("<\/td>");
document.write("  <\/tr>");
document.write("  ");
document.write("  <tr>");
document.write("    <td valign=\"middle\"  width=\"20%\" height=\"110\" align =\"center\" ><a href=\"http:\/\/www.ammasguide.com\" target=”_blank”><img src=\"img\/foodfestival.jpg\" width=\"100%\" height=\"110\" \/><\/a><\/td>");
document.write("    <td align=\"center\" valign=\"middle\"><img src=\"img\/hori-ban-otherpages.jpg\" alt=\"banner\" width=\"100%\" height=\"110\" align=\"middle\" \/><\/td>");
document.write("    <td width=\"20%\" height=\"110\" align =\"center\" valign=\"middle\"><a href=\"http:\/\/www.ammasguide.com\" target=”_blank”><img src=\"img\/ymg-banner.jpg\" width=\"100%\" height=\"110\" \/><\/a>");
document.write("<\/br><\/td>");
document.write("  <\/tr>");
document.write("<\/table>");
document.write("<table width=\"100%\" >");
document.write("  <tr bgcolor=\"#FFFFFF\">");
document.write("    <td width=\"10%\" align=\"left\" bgcolor=\"#E0E0E0\"> <a href=\"about.html\"  ><strong><font face=\"Arial\" size=\"2\" color=\"black\">About <\/font><\/strong><\/td>");
document.write("    <td width=\"10%\" align=\"left\" bgcolor=\"#E0E0E0\"> <a href=\"contact.html\"  ><strong><font face=\"Arial\" size=\"2\" color=\"black\">Contact <\/font><\/strong><\/td>");
document.write("    <td width=\"20%\" align=\"left\" bgcolor=\"#E0E0E0\"> <a href=\"ack.html\"  ><strong><font face=\"Arial\" size=\"2\" color=\"black\">Acknowledgements <\/font><\/strong><\/td>");
document.write("	<td align=\"right\" bgcolor=\"#E0E0E0\"><a href=\"disc.html\"  ><strong><font face=\"Arial\" size=\"2\" color=\"black\">Disclaimer<\/font><\/strong><\/td>");
document.write("  <\/tr>");
document.write("<\/table>");
document.write("");
document.write("");
