document.write(" <div style=\"border:1px solid blue;\">");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#0000FF\"   >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"center\" valign=\"middle\" > &nbsp;<\/strong><img src=\"img\/vaishnav.JPG\" width=\"18\" height=\"18\" border=\"0\" \/><strong><font face=\"Arial\" size=\"2\" color=\"white\"> &nbsp;&nbsp; 108 Divya Desams <\/font>  <\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("  <\/table> ");
document.write("<!----**************************************************-------------------------------------------------------------------------->	   ");
document.write("  <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Thondai Nadu (22\/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr> ");
document.write("		<td  width=100% align=\"centre\"  style= \" text-align: center;\"  bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\"  color=\"#FFFF00\" >Chennai & around <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write(" <\/table>");
document.write("<ul class=\"nav\" > ");
document.write("      ");
document.write("      <li><a href=\"tiruallikeni.html\"> &#45 Thiruallikeni<\/a><\/li>");
document.write(" 	<li><a title=\"under Construction\" href=\"\"> &#45Sholingar<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"\"> &#45Thiruneermalai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"\"> &#45Thiru kadalmalai<\/a><\/li>");
document.write("	<li><a href=\"thiruvidenthai.htm\"> &#45Thiruvidanthai<\/a><\/li>");
document.write("	<li><a href=\"thiruninravoor.html\"> &#45Thinnanoor<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"\"> &#45Tiruvallore<\/a><\/li>");
document.write("<\/ul>");
document.write("");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Kanchipuram &amp; around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("<\/table>");
document.write("<ul class=\"nav\">  ");
document.write("	   	");
document.write("	   <li><a href=\"nilathingal.html\"> &#45Nilathingal<\/a><\/li>");
document.write("	   <li><a href=\"ashtapuja.html\"> &#45Ashtapuyakaram<\/a><\/li>");
document.write("	   <li><a href=\"thirukalvanoor.html\"> &#45Thiru Kalvanoor<\/a><\/li>");
document.write("		<li><a href=\"vaikunta.html\"> &#45Thiru Parameswara &nbsp;&nbsp;Vinnagaram <\/a><\/li>");
document.write("		<li><a href=\"thiruooragam.html\"> &#45Thiru Ooragam<\/a><\/li>");
document.write("");
document.write("<div onClick=\"openClose('ddm2')\" class=\"main\"><span id=\"tick_ddm2\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"ddm2\" class=\"links\">");
document.write("	  		");
document.write("		<li><a href=\"yadodkari.html\"> &#45Thiruvekka<\/a><\/li>");
document.write("		<li><a href=\"thirukaaragam.html\"> &#45Thiru Kaaragam<\/a><\/li>");
document.write("		<li><a href=\"thirukaarvanam.html\"> &#45Thirukaar Vaanam<\/a><\/li>");
document.write("		<li><a href=\"pavalavannar.html\"> &#45Thiru Pavalavannam<\/a><\/li>");
document.write("		<li><a href=\"thiruvelukkai.html\"> &#45Thiru Velukkai<\/a><\/li>");
document.write("		<li><a href=\"thiruthanka.html\"> &#45Thiruthanka (Thoopul)<\/a><\/li>");
document.write("		<li><a href=\"varadaraja.html\"> &#45 Thiru Kachi- Kanchi<\/a><\/li>");
document.write("		<li><a href=\"thirupukkuzhi.html\"> &#45Tiruputkuzhi<\/a><\/li>");
document.write("		<li><a href=\"thiruneeragam.html\"> &#45Thiru Neeragam <\/a>");
document.write("		<\/li><li><a href=\"pandavathudhar.html\"> &#45Thiru Paadagam <\/a><\/li>");
document.write("		");
document.write("");
document.write("<\/ul>");
document.write("");
document.write("");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Chozha Nadu (40\/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\"  > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Seerkazhi & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write(" <\/table>");
document.write(" <ul class=\"nav\" >	 ");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Sirkazhi<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Arimeya Vinnagaram<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Vann Purushotaman<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Vaheendrapuram<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Kavalampaadi<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thirunaangur<\/a><\/li>");
document.write("<div onClick=\"openClose('seer')\" class=\"main\"><span id=\"tick_seer\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"seer\" class=\"links\">");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Sempon Sei Kovil<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Manimaada Kovil<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Vaigundha Vinnagaram<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Devanaar Thogai<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Thetri Aambalam<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Manikkoodam<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Vellakkulam <\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Paarthanpalli<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvalli<\/a><\/li>");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"   bgcolor=\"#6699CC\" > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Mayavaram & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write(" <\/table>	 ");
document.write("<ul class=\"nav\" >	   	   ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thalaichanga<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvazhuntoor<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Chidambaram<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiru-nagai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Sirupuliyur<\/a><\/li>");
document.write("	");
document.write("<\/ul>");
document.write("<div onClick=\"openClose('may')\" class=\"main\"><span id=\"tick_may\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"may\" class=\"links\">");
document.write("	  ");
document.write("<ul class=\"nav\" >	  ");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Therezhendur<\/a><\/li>");
document.write("	");
document.write("	<li><a title=\"under Construction\" href=\"#\" &#45Thirukannangudi<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\" &#45ThiruKannapuram<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\" &#45Thiruindhalur<\/a><\/li>	  ");
document.write("<\/ul>");
document.write("<\/div>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Kumbakonam & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	 ");
document.write("<ul class=\"nav\" >	   ");
document.write("<li><a href=\"sarngapani.html\"> &#45Thiru Kudanthai<\/a><\/li> ");
document.write("<li><a href=\"velliyankudi.html\"> &#45Thiruvelliyankudi<\/a><\/li> ");
document.write("<li><a href=\"thirunarayur.html\"> &#45Thirunaraiyur (Nachiar Koil)<\/a><\/li> ");
document.write("");
document.write("<div onClick=\"openClose('kum2')\" class=\"main\"><span id=\"tick_kum2\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kum2\" class=\"links\">");
document.write("");
document.write("<li><a href=\"nathankoil.html\"> &#45Nathan kovil<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiruccherai<\/a><\/li> ");
document.write("<li><a href=\"oppilliappan.html\"> &#45Thiru Vinnagar<\/a><\/li> ");
document.write("<li><a href=\"thiruadanoor.html\"> &#45Thiru Aadhanoor<\/a><\/li>");
document.write("<li><a href=\"kabithalam.html\"> &#45Kapisthalam<\/a><\/li> ");
document.write("<li><a href=\"thirukudalur.html\"> &#45Thirukoodalur<\/a><\/li> ");
document.write("<li><a href=\"pboothankudi.html\"> &#45Pullam Bhoothankudi<\/a><\/li> ");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thirukkannamangai<\/a><\/li> ");
document.write("");
document.write("<\/ul>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write(" <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Trichy & around<\/font><\/strong><\/td>");
document.write(" <\/tr>");
document.write(" <\/table>	 ");
document.write("<ul class=\"nav\">");
document.write("");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Srirangam<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thirupper Nagar<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Anbil<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Vellarai<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thirukkarambanoor<\/a><\/li>");
document.write("<li><a href=\"Thirukkozhi.html\"> &#45Thirukkozhi<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Tanjore<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45 Thiru Kandiyur<\/a><\/li>");
document.write("<\/ul>	   	   ");
document.write("<!--  **** -------------------------------------------------------------------------------------------------------------------->	  ");
document.write("<table  width=100% border=\"0\"bgcolor=\"#99CCFF\" >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Nadu Nadu (2 \/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\" bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Cuddalore dist <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	 ");
document.write("<ul class=\"nav\" >	    	    ");
document.write("	  <li><a title=\"under Construction\" href=\"#\"\/\/#-temples.blogspot.com\/2009\/06\/sri-trivikramaswamy-temple-thirukovilur.html\"> &#45Thirukovilur<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"\/\/#-temples.blogspot.com\/2009\/07\/sri-deyva-nayaga-perumal-temple.html\"> &#45Thiruvaheendrapuram<\/a><\/li>");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<!--  **** -------------------------------------------------------------------------------------------------------------------->	");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Malai Nadu <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr> ");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Kerala State(13\/108) <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	");
document.write("<ul class=\"nav\"	>    	    ");
document.write("	  <li><a title=\"under Construction\" href=\"#\"> &#45Thiruvananthapuram	<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvanvandoor<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvaaranvilai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirupuliyoor<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirucchenkundroor<\/a><\/li>");
document.write("	<div onClick=\"openClose('ker')\" class=\"main\"><span id=\"tick_ker\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"ker\" class=\"links\">");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirukkadithaanam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvalvaazh<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirumoozhikkalam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirukkaatkarai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Naavaay<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvazhmarban (KK)<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvattarur (KK)<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvithuvakkodu<\/a><\/li>");
document.write("");
document.write("<\/ul>");
document.write("<!--  **** -------------------------------------------------------------------------------------------------------------------->");
document.write("	");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Pandiya Nadu (18\/108) <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" ><strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\" >Madurai & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	");
document.write("	   ");
document.write("<ul class=\"nav\">	     	    ");
document.write("	  <li><a title=\"under Construction\" href=\"#\"> &#45Thirumalirunsolai<\/a><\/li> ");
document.write("	 <li><a title=\"under Construction\" href=\"#\"> &#45Vanama malai<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruthankaal<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirukkoodal<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Moghur<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruppullanni<\/a><\/li>");
document.write("	<div onClick=\"openClose('mdu')\" class=\"main\"><span id=\"tick_mdu\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"mdu\" class=\"links\"> ");
document.write("	<li><a href=\"thirukoshtiyur.html\"> &#45Thirukoshtiyur<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirumeyyam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirunagari<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45ThenThirupperai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirukoolur<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Sri Villiputhur<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Tholaivillimangalam<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruppulingudi<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvaragunamangai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45SriVaikundami<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruccheerivaramangai<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thirukkurungudi<\/a><\/li> ");
document.write("");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<!--  **** -------------------------------------------------------------------------------------------------------------------->");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Vada Nadu (11\/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" ><strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">North India<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	");
document.write("	   ");
document.write("<ul class=\"nav\">");
document.write("    <li><a title=\"under Construction\" href=\"#\"> &#45Ayodhi<\/a><\/li>	     	    ");
document.write("	  <li><a title=\"under Construction\" href=\"#\"> &#45Thiru Naimisaranyam<\/a><\/li>");
document.write(" 	<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Salagramam (Nepal)<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Kadi Nagar-Devaprayag <\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruppirudhi<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Brindhavanam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Dwaraka<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Badrinath<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Thiruvaaipadi<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Ahobilam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"#\"> &#45Tirupati<\/a><\/li>");
document.write("");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<ul class=\"nav\" >");
document.write("  ");
document.write("     <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Sakthi Peedams <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"#\"><font size=\"2\"> &#45 Kanchipuram<\/font><\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"#\">&#45 Varanasi<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"#\">&#45 Mysore<\/a><\/li>");
document.write("	   <div onClick=\"openClose('sp')\" class=\"main\"><span id=\"tick_sp\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"sp\" class=\"links\">");
document.write("      <li><a title=\"under Construction\"  href=\"#\">&#45 Jwalamukhi<\/a><\/li>");
document.write(" <\/ul>");
document.write(" ");
document.write(" <ul class=\"nav\" >");
document.write("	  ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Pancha Bootha Sthalangal <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     <li><a title=\"under Construction\"  href=\"#\"> &#45 Chidambaram<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"#\"> &#45 Kanchipuram<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Kalahasthi<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\">&#45 Tiruvannamalai<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"#\">&#45 Tiruvanai Koil<\/a><\/li>");
document.write("    ");
document.write("      ");
document.write("  <\/ul>");
document.write(" <ul class=\"nav\" >      ");
document.write("      ");
document.write("     ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Arupadai Veedu <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"#\"> &#45 Palani<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Pazhamudircholai<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Swamimalai<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Tirutani<\/a><\/li>");
document.write("        <div onClick=\"openClose('aru')\" class=\"main\"><span id=\"tick_aru\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"aru\" class=\"links\"> ");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Tiruchendur<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Tiruparamkundram<\/a><\/li>      ");
document.write("  <\/ul>");
document.write("  <ul class=\"nav\" >  ");
document.write("  <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Ashta Vinayak <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("	  <li><a   href=\"morgaon.html\"> &#45Moreshwar- Morgaon<\/a><\/li>");
document.write("	  <li><a   href=\"theur.html\"> &#45 Chintamani - Theur<\/a><\/li>");
document.write("	  <li><a href=\"sidhatek.html\"> &#45 Sidhivinayak - Siddhatek<\/a><\/li>");
document.write("	  <li><a  href=\"ranjangaon.html\"> &#45 Mahaganapathi-Ranjangaon<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45Vignahar - Ozar<\/a><\/li>     ");
document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Girijatmaj - Lenyadri<\/a><\/li>");

document.write("	  <li><a title=\"under Construction\"  href=\"#\"> &#45 Varadavinayak - Mahad<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"#\"> &#45 Baleshwar-Pali<\/a><\/li>");
document.write("  <\/ul>");
document.write("  ");
document.write("  ");
document.write("  <ul class=\"nav\" > ");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Navagraha Sthalas <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\" href=\"#\"> &#45 Thirunallar -Sani<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thirunageswaram - Raghu<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Trivenkadu - Budan<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Keezhaperumpallam - Kethu<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Alangudi - Guru<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Kanjanoor - Sukran<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Vaitheeswarankoil - Sevvai<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thingaloor - Chandran<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Suriyanar Koil -Suryan<\/a><\/li>");
document.write("");
document.write("<\/ul>");
document.write("   ");
document.write("  <ul class=\"nav\"  >  ");
document.write("      ");
document.write("	  <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Hindu Festivals <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"#\"> &#45 Pongal<\/a><\/li>");
document.write("	   <div onClick=\"openClose('fest')\" class=\"main\"><span id=\"tick_fest\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click for More ...<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"fest\" class=\"links\">");
document.write("             ");
document.write("      ");
document.write("        ");
document.write("    <\/ul>");
document.write("	<hr \/>");
document.write("	<\/div>");
