document.write(" <div style=\"border:1px solid blue;\">");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#0000FF\"   >");
document.write("      ");
document.write("		<tr>");
document.write("		<td  align=\"center\" valign=\"middle\" > &nbsp;<font face=\"Arial\" size=\"2\" color=\"white\"> &nbsp;&nbsp; 108 Divya Desams <\/font>  <\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("  <\/table> ");
document.write("<!----************-------------------------------------------------------->	   ");
document.write("  <table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Thondai Naadu (22\/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr> ");
document.write("		<td  width=100% align=\"centre\"  style= \" text-align: center;\"  bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\"  color=\"#FFFF00\" >Chennai & around <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write(" <\/table>");
document.write("<ul class=\"nav\" > ");
document.write("      ");
document.write("      <li><a href=\"tiruallikeni.html\"> &#45Thiruallikeni<\/a><\/li>");
document.write(" 	<li><a  href=\"sholingur.html\"> &#45Thirukadigai<\/a><\/li>");
document.write("	<li><a  href=\"thiruneermalai.html\"> &#45Thiruneermalai<\/a><\/li>");
document.write("	<li><a  href=\"thirukadalmallai.html\"> &#45Thiru kadalmalai<\/a><\/li>");
document.write("	<li><a href=\"thiruvidenthai.htm\"> &#45Thiruvidanthai<\/a><\/li>");
document.write("	<li><a href=\"thiruninravoor.html\"> &#45Thinnanoor<\/a><\/li>");
document.write("	<li><a  href=\"thiruvaluri.html\"> &#45Tiruvallore<\/a><\/li>");
document.write("<\/ul>");
document.write("");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Kanchipuram &amp; around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("<\/table>");
document.write("<ul class=\"nav\">  ");
document.write("	   	");
document.write("	   <li><a href=\"nilathingal.html\"> &#45Nilathingal<\/a><\/li>");
document.write("	   <li><a href=\"ashtapuja.html\"> &#45Ashtapuyakaram<\/a><\/li>");
document.write("	   <li><a href=\"thirukalvanoor.html\"> &#45Thiru Kalvanoor<\/a><\/li>");
document.write("		<li><a href=\"vaikunta.html\"> &#45Thiru Parameswara &nbsp;&nbsp;Vinnagaram <\/a><\/li>");
document.write("		<li><a href=\"thiruooragam.html\"> &#45Thiru Ooragam<\/a><\/li>");
document.write("");
document.write("<div onClick=\"openClose('ddm2')\" class=\"main\"><span id=\"tick_ddm2\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"ddm2\" class=\"links\">");
document.write("	  		");
document.write("		<li><a href=\"yadodkari.html\"> &#45Thiruvekka<\/a><\/li>");
document.write("		<li><a href=\"thirukaaragam.html\"> &#45Thiru Kaaragam<\/a><\/li>");
document.write("		<li><a href=\"thirukaarvanam.html\"> &#45Thirukaar Vaanam<\/a><\/li>");
document.write("		<li><a href=\"pavalavannar.html\"> &#45Thiru Pavalavannam<\/a><\/li>");
document.write("		<li><a href=\"thiruvelukkai.html\"> &#45Thiru Velukkai<\/a><\/li>");
document.write("		<li><a href=\"thiruthanka.html\"> &#45Thiruthanka (Thoopul)<\/a><\/li>");
document.write("		<li><a href=\"varadaraja.html\"> &#45 Thiru Kachi- Kanchi<\/a><\/li>");
document.write("		<li><a href=\"thirupukkuzhi.html\"> &#45Tiruputkuzhi<\/a><\/li>");
document.write("		<li><a href=\"thiruneeragam.html\"> &#45Thiru Neeragam <\/a>");
document.write("		<\/li><li><a href=\"pandavathudhar.html\"> &#45Thiru Paadagam <\/a><\/li>");
document.write("		");
document.write("");
document.write("<\/ul>");
document.write("");
document.write("");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Chozha  Naadu (40\/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\"  > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Seerkazhi & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write(" <\/table>");
document.write(" <ul class=\"nav\" >	 ");
document.write("<li><a  href=\"sirkazhi.html\"> &#45Sirkazhi<\/a><\/li>");
document.write("<li><a  href=\"thiruarimeyavinnagaram.html\"> &#45Thiru Arimeya Vinnagaram<\/a><\/li>");
document.write("<li><a href=\"thiruvanpurushothaman.html\"> &#45Thiru Vann Purushotaman<\/a><\/li>");
//document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thiru Vaheendrapuram<\/a><\/li>");
document.write("<li><a  href=\"thirukavalampadi.html\"> &#45Thiru Kavalampaadi<\/a><\/li>");
//document.write("<li><a title=\"under Construction\" href=\"#\"> &#45Thirunaangur<\/a><\/li>");
document.write("<div onClick=\"openClose('seer')\" class=\"main\"><span id=\"tick_seer\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"seer\" class=\"links\">");
document.write("<li><a  href=\"semponseikoil.html\"> &#45Thiru Sempon Sei Kovil<\/a><\/li>");
document.write("<li><a  href=\"thirumanimadakoil.html\"> &#45Thiru Manimaada Kovil<\/a><\/li>");
document.write("<li><a  href=\"thiruvaikundahvinnagaram.html\"> &#45Vaigundha Vinnagaram<\/a><\/li>");
document.write("<li><a  href=\"thiruthevanarthogai.html\"> &#45Thiru Devanaar Thogai<\/a><\/li>");
document.write("<li><a  href=\"thiruthetriambalam.html\"> &#45Thiru Thetri Aambalam<\/a><\/li>");
document.write("<li><a  href=\"thirumanikoodam.html\"> &#45Thiru Manikkoodam<\/a><\/li>");
document.write("<li><a  href=\"thiruvellakulam.html\"> &#45Thiru Vellakkulam <\/a><\/li>");
document.write("<li><a  href=\"thiruparthanpall.html\"> &#45Thiru Paarthanpalli<\/a><\/li>");
document.write("<li><a  href=\"thiruvali-thirunagari.html\"> &#45Thiruvali-ThiruNagari<\/a><\/li>");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"   bgcolor=\"#6699CC\" > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Mayavaram & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write(" <\/table>	 ");
document.write("<ul class=\"nav\" >	   	   ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thalaichanga<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvazhuntoor<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Chidambaram<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiru-nagai<\/a><\/li>");
document.write("	<li><a  href=\"sirupuliyur.html\"> &#45Sirupuliyur<\/a><\/li>");
document.write("	");
document.write("<\/ul>");
document.write("<div onClick=\"openClose('may')\" class=\"main\"><span id=\"tick_may\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"may\" class=\"links\">");
document.write("	  ");
document.write("<ul class=\"nav\" >	  ");
document.write("     <li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Therezhendur<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\" >&#45Thirukannangudi<\/a><\/li>");
document.write("	<li><a  href=\"thirukannapuram.html\" >&#45ThiruKannapuram<\/a><\/li>");
document.write("	<li><a  href=\"thiruindalur.html\"> &#45Thiruindhalur<\/a><\/li>	  ");
document.write("<\/ul>");
document.write("<\/div>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" > &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Kumbakonam & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	 ");
document.write("<ul class=\"nav\" >	   ");
document.write("<li><a href=\"sarngapani.html\"> &#45Thiru Kudanthai<\/a><\/li> ");
document.write("<li><a href=\"velliyankudi.html\"> &#45Thiruvelliyankudi<\/a><\/li> ");
document.write("<li><a href=\"thirunarayur.html\"> &#45Thirunaraiyur (Nachiar Koil)<\/a><\/li> ");
document.write("");
document.write("<div onClick=\"openClose('kum2')\" class=\"main\"><span id=\"tick_kum2\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"kum2\" class=\"links\">");
document.write("");
document.write("<li><a href=\"nathankoil.html\"> &#45Nathan kovil<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruccherai<\/a><\/li> ");
document.write("<li><a href=\"oppilliappan.html\"> &#45Thiru Vinnagar<\/a><\/li> ");
document.write("<li><a href=\"thiruadanoor.html\"> &#45Thiru Aadhanoor<\/a><\/li>");
document.write("<li><a href=\"kabithalam.html\"> &#45Kapisthalam<\/a><\/li> ");
document.write("<li><a href=\"thirukudalur.html\"> &#45Thirukoodalur<\/a><\/li> ");
document.write("<li><a href=\"pboothankudi.html\"> &#45Pullam Bhoothankudi<\/a><\/li> ");
document.write("<li><a href=\"thirukanmangai.html\"> &#45Thirukkannamangai<\/a><\/li> ");
document.write("");
document.write("<\/ul>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 ");
document.write(" <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Trichy & around<\/font><\/strong><\/td>");
document.write(" <\/tr>");
document.write(" <\/table>	 ");
document.write("<ul class=\"nav\">");
document.write("");
document.write("<li><a  href=\"srirangam.html\"> &#45Srirangam<\/a><\/li>");
document.write("<li><a  href=\"thiruperrurkoiladi.html\"> &#45Thirupper Nagar<\/a><\/li>");
document.write("<li><a  href=\"anbil.html\"> &#45Thiru Anbil<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiru Vellarai<\/a><\/li>");
document.write("<li><a  href=\"thirukarambanoor.html\"> &#45Thirukkarambanoor<\/a><\/li>");
document.write("<li><a href=\"Thirukkozhi.html\"> &#45Thirukkozhi<\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Tanjore<\/a><\/li>");
document.write("<li><a  href=\"thirukandiyur.html\"> &#45 Thiru Kandiyur<\/a><\/li>");
document.write("<\/ul>	   	   ");
document.write("<!--  ****--------------------------------------------------------------------->	  ");
document.write("<table  width=100% border=\"0\"bgcolor=\"#99CCFF\" >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Nadu Naadu (2 \/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\" bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Cuddalore dist <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	 ");
document.write("<ul class=\"nav\" >	    	    ");
document.write("	  <li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirukovilur<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"\"> &#45Thiruvaheendrapuram<\/a><\/li>");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<!--  ****-------------------------------------------------------------------------->	");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Malai Naadu <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr> ");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">Kerala State(13\/108) <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	");
document.write("<ul class=\"nav\"	>    	    ");
document.write("	  <li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvananthapuram	<\/a><\/li>");
document.write("	<li><a  href=\"thiruvanvandoor.html\"> &#45Thiruvanvandoor<\/a><\/li>");
document.write("	<li><a  href=\"Thiruaranmula.html\"> &#45Thiruvaaran Vilai<\/a><\/li>");
document.write("	<li><a  href=\"Thirupuliyur.html\"> &#45Thirupuliyoor<\/a><\/li>");
document.write("	<li><a href=\"Thirucchenkundroor.html\"> &#45Thirucchenkundroor<\/a><\/li>");
document.write("	<div onClick=\"openClose('ker')\" class=\"main\"><span id=\"tick_ker\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"ker\" class=\"links\">");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirukkadithaanam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvalvaazh<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirumoozhikkalam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirukkaatkarai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiru Naavaay<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvazhmarban <\/a><\/li>");
document.write("<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvattar <\/a><\/li>");
document.write("<li><a href=\"Thirumittacode.html\"> &#45Thiruvithuvakkodu<\/a><\/li>");
document.write("");
document.write("<\/ul>");
document.write("<!--  **** ----------------------------------------------------------------->");
document.write("	");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Pandiya Naadu (18\/108) <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" ><strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\" >Madurai & around<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	");
document.write("	   ");
document.write("<ul class=\"nav\">	     	    ");
document.write("	  <li><a  href=\"alagarkoil.html\"> &#45Thirumalirunsolai<\/a><\/li> ");
document.write("	 <li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Vanama malai<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruthankaal<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirukkoodal<\/a><\/li> ");
document.write("	<li><a href=\"thirumokur.html\"> &#45Thiru Moghur<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruppullanni<\/a><\/li>");
document.write("	<div onClick=\"openClose('mdu')\" class=\"main\"><span id=\"tick_mdu\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"mdu\" class=\"links\"> ");
document.write("	<li><a href=\"thirukoshtiyur.html\"> &#45Thirukoshtiyur<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirumeyyam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirunagari<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45ThenThirupperai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirukoolur<\/a><\/li> ");
document.write("	<li><a  href=\"srivilliputhur.html\"> &#45Sri Villiputhur<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Tholaivillimangalam<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruppulingudi<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvaragunamangai<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45SriVaikundam<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruccheerivaramangai<\/a><\/li> ");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thirukkurungudi<\/a><\/li> ");
document.write("");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<!--  **** ------------------------------------------------------>");
document.write("<table  width=100% border=\"0\" bgcolor=\"#99CCFF\"  >");
document.write("	 <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font face=\"Arial\" size=\"2\" color=\"black\" >Vada Naadu (11\/108)<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <tr>");
document.write("		<td width=100% align=\"centre\" style= \" text-align: center;\"  bgcolor=\"#6699CC\" ><strong><font face=\"Arial\" size=\"2\" color=\"#FFFF00\">North India<\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   <\/table>	");
document.write("	   ");
document.write("<ul class=\"nav\">");
document.write("    <li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Ayodhi<\/a><\/li>	     	    ");
document.write("	  <li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiru Naimisaranyam<\/a><\/li>");
document.write(" 	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiru Salagramam (Nepal)<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Kadi Nagar-Devaprayag <\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruppirudhi<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Brindhavanam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Dwaraka<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Badrinath<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Thiruvaaipadi<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Ahobilam<\/a><\/li>");
document.write("	<li><a title=\"under Construction\" href=\"underconstruction.html\"> &#45Tirupati<\/a><\/li>");
document.write("");
document.write("");
document.write("");
document.write("<\/ul>");
document.write("<ul class=\"nav\" >");
document.write("  ");
document.write("     <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >");
document.write("      ");
document.write("		<tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Sakthi Peedams <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\"><font size=\"2\"> &#45 Kanchipuram<\/font><\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Varanasi<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Mysore<\/a><\/li>");
document.write("	   <div onClick=\"openClose('sp')\" class=\"main\"><span id=\"tick_sp\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"sp\" class=\"links\">");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Jwalamukhi<\/a><\/li>");
document.write(" <\/ul>");
document.write(" ");
document.write(" <ul class=\"nav\" >");
document.write("	  ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Pancha Bootha Sthalangal <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     <li><a title=\"under Construction\"  href=\"underconstruction.html\"> &#45 Chidambaram<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\"> &#45 Kanchipuram<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Kalahasthi<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Tiruvannamalai<\/a><\/li>");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\">&#45 Tiruvanai Koil<\/a><\/li>");
document.write("    ");
document.write("      ");
document.write("  <\/ul>");
document.write(" <ul class=\"nav\" >      ");
document.write("      ");
document.write("     ");
document.write("   <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Arupadai Veedu <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\"> &#45 Palani<\/a><\/li>");
document.write("	  <li><a   href=\"pazhacholai.html\"> &#45 Pazhamudircholai<\/a><\/li>");
document.write("	  <li><a  href=\"swamimalai.html\"> &#45 Swamimalai<\/a><\/li>");
document.write("	  <li><a title=\"under Construction\"  href=\"underconstruction.html\"> &#45 Tirutani<\/a><\/li>");
document.write("        <div onClick=\"openClose('aru')\" class=\"main\"><span id=\"tick_aru\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"aru\" class=\"links\"> ");
document.write("	  <li><a title=\"under Construction\"  href=\"underconstruction.html\"> &#45 Tiruchendur<\/a><\/li>");
document.write("	  <li><a   href=\"thiruparankunram.html\"> &#45 Tiruparamkundram<\/a><\/li>      ");
document.write("  <\/ul>");
document.write("  <ul class=\"nav\" >  ");
document.write("  <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Ashta Vinayak <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("	  <li><a   href=\"morgaon.html\"> &#45Moreshwar- Morgaon<\/a><\/li>");
document.write("	  <li><a   href=\"theur.html\"> &#45 Chintamani - Theur<\/a><\/li>");
document.write("	  <li><a href=\"sidhatek.html\"> &#45 Sidhivinayak - Siddhatek<\/a><\/li>");
document.write("	  <li><a  href=\"ranjangaon.html\"> &#45 Mahaganapathi-Ranjangaon<\/a><\/li>");
document.write("	  <li><a  href=\"ozar.html\"> &#45Vignahar - Ozar<\/a><\/li>     ");
document.write("	  <li><a   href=\"leyandri.html\"> &#45 Girijatmaj - Lenyadri<\/a><\/li>");

document.write("	  <li><a  href=\"mahad.html\"> &#45 Varadavinayak - Mahad<\/a><\/li>");
document.write("      <li><a  href=\"pali.html\"> &#45 Baleshwar-Pali<\/a><\/li>");
document.write("  <\/ul>");
document.write("  ");
document.write("  ");
document.write("  <ul class=\"nav\" > ");
document.write(" <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Navagraha Sthalas <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a  href=\"thirunallaru.html\"> &#45 Thirunallar -Sani<\/a><\/li>");
document.write("<li><a  href=\"thirunageswaram.html\"> &#45Thirunageswaram - Raghu<\/a><\/li>");
document.write("<li><a  href=\"thiruvengadu.html\"> &#45Trivengadu - Budan<\/a><\/li>");
document.write("<li><a href=\"kethu.html\"> &#45Keezhaperumpallam - Kethu<\/a><\/li>");
document.write("<li><a  href=\"alangudi.html\"> &#45Alangudi - Guru<\/a><\/li>");
document.write("<li><a  href=\"kanjanur.html\"> &#45Kanjanoor - Sukran<\/a><\/li>");
document.write("<li><a href=\"sevvai.html\"> &#45Vaitheeswarankoil - Sevvai<\/a><\/li>");
document.write("<li><a href=\"thingalaur.html\"> &#45Thingaloor - Chandran<\/a><\/li>");
document.write("<li><a href=\"suriyanar.html\"> &#45Suriyanar Koil -Suryan<\/a><\/li>");
document.write("");
document.write("<\/ul>");
document.write("   ");
document.write("  <ul class=\"nav\"  >  ");
document.write("      ");
document.write("	  <table  width=100% border=\"0\" bgcolor=\"#0000FF\"  >   ");
document.write("   <tr>");
document.write("		<td width=100% align=\"centre\"> &nbsp;<strong><font size=\"2\" color=\"white\">Hindu Festivals <\/font><\/strong><\/td>");
document.write("       <\/tr>");
document.write("	   ");
document.write("       <\/table> ");
document.write("     ");
document.write("      <li><a title=\"under Construction\"  href=\"underconstruction.html\"> &#45 Pongal<\/a><\/li>");
document.write("	   <div onClick=\"openClose('fest')\" class=\"main\"><span id=\"tick_fest\">+<\/span> <span class=\"mainLink\"><strong><font size=\"1\">Click to expand/collapse..<\/font><\/strong><\/span><\/div>");
document.write("      <div id=\"fest\" class=\"links\">");
document.write("             ");
document.write("      ");
document.write("        ");
document.write("    <\/ul>");
document.write("	<hr \/>");
document.write("	<\/div>");
